<?php
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    function randomString($length = 10) {
        $characters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }
    if ($_SERVER['REQUEST_URI'] == '/register/') {
        $nameserverfile = fopen('../database/nameserver.nsf', 'a+');
    }
    else {
        $nameserverfile = fopen('database/nameserver.nsf', 'a+');
    }
    $joindata = $_POST['domain'] . ' ' . $_POST['ip'];
    $code = randomString($length = 6);
    $delcode = randomString($legnth = 8);
    $linkpage = "https://domainiac.diamonddemon.me/link.php?code=" . $code;
    $newdata = PHP_EOL . $_POST['domain'] . ' ' . $_POST['ip'] . ' ' . $code . " " . $delcode;
    if (substr_count($joindata, " ") == 1) {
        if (filter_var($_POST['ip'], FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) == $_POST['ip']) {
            fwrite($nameserverfile, $newdata);
            $exit = "Success!";
        }
        else {
            $exit = "Error: failed to bypass filter 2";
        }
    }
    else {
        $exit = "Error: failed to bypass filter 1";
    }
}
else {
    $code = "";
    $delcode = "";
    $linkpage = "";
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Register a domain now!</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Domainiac domain registry</a></h1>
		<form id="form_4906" class="appnitro"  method="post" action="/register.php">
					<div class="form_description">
			<h2>Domainiac domain registry</h2>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Domain </label>
		<div>
			<input id="element_1" name="domain" class="element text medium" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_1"><small>ASCII only please</small></p> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">IP </label>
		<div>
			<input id="element_2" name="ip" class="element text medium" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_2"><small>Numbers only - 0.0.0.0-255.255.255.255</small></p> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="4906" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" /><p><?php echo $exit; ?></p><br></p><p>Link code: <?php echo $code; ?> Delete code (do not share): <?php echo $delcode; ?> Link page (share me): <a href=<?php echo $linkpage; ?>><?php echo $linkpage; ?></a> </p>
		</li>
		
					</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>